name: Tests
on: workflow_dispatch
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Cache .m2 repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-repository-${{ hashFiles('**/pom.xml') }}
          save-always: true
      - name: Cache Maven wrapper
        uses: actions/cache@v4
        with:
          path: ~/.m2/wrapper
          key: maven-wrapper-${{ hashFiles('**/mvnw') }}
          save-always: true
      - name: Set up Eclipse Temurin JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'
      - name: Build and test LSP4MP jdt component
        run: cd microprofile.jdt && ./mvnw -B -U clean verify && cd ..
      - name: Build and test LSP4MP language server component
        run: cd microprofile.ls/org.eclipse.lsp4mp.ls && ./mvnw -B -U clean verify
